name: dfast_qc
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - python==3.11
  - mash
  - skani
  - gsl==2.6
  - hmmer
  - prodigal
  - blast
  - pip:
    - checkm-genome
    - ete3
    - more-itertools
    - peewee